version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctime
      MYSQL_USER: ctimeuser
      MYSQL_PASSWORD: ctimepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://ctimeuser:ctimepassword@db:3306/ctime
    volumes:
      - .:/app
    command: ["flask", "run", "--host=0.0.0.0"]

volumes:
  mysql-data: