version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctime
      MYSQL_USER: ctimeuser
      MYSQL_PASSWORD: ctimepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      CONNECTION_STRING: mysql+pymysql://ctimeuser:ctimepassword@db:3306/ctime
      SECRET_KEY: <YOUR_SECRET_KEY>
    volumes:
      - .:/app
    command: >
      sh -c 'gunicorn -b 0.0.0.0:5000 "app.app:create_app()"'

volumes:
  mysql-data:
