version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
  node-executor:
    docker:
      - image: cimg/node:23.8.0
    working_directory: ~/repo

jobs:
  changesets-version: # Renamed from semantic-release
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Set npm global prefix
          command: |
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
      - run:
          name: Install Changesets CLI
          command: npm install -g @changesets/cli
      - run:
          name: Initialize Changesets
          command: changeset init
      - run:
          name: Determine Release Version with Changesets
          command: |
            VERSION=$(changeset version --no-commit --dry-run | grep -oP 'Bumping version to \K([\d.]+)' || echo "latest")
            echo "export RELEASE_VERSION=$VERSION" >> $BASH_ENV
      - persist_to_workspace:
          root: .
          paths:
            - .
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Keep GITHUB_TOKEN for potential future GitHub actions

  build-and-push:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t soarn/ctime:latest .
            docker tag soarn/ctime:latest soarn/ctime:$RELEASE_VERSION
            docker tag soarn/ctime:latest ghcr.io/${CIRCLE_PROJECT_USERNAME}/ctime:latest
            docker tag soarn/ctime:latest ghcr.io/${CIRCLE_PROJECT_USERNAME}/ctime:$RELEASE_VERSION
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push to DockerHub
          command: |
            docker push soarn/ctime:latest
            docker push soarn/ctime:$RELEASE_VERSION
      - run:
          name: Login to GHCR
          command: echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - run:
          name: Push to GHCR
          command: |
            docker push ghcr.io/${CIRCLE_PROJECT_USERNAME}/ctime:latest
            docker push ghcr.io/${CIRCLE_PROJECT_USERNAME}/ctime:$RELEASE_VERSION

  sentry-release:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Sentry CLI
          command: pip install sentry-cli
      - run:
          name: Create Sentry Release
          command: |
            export SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
            export SENTRY_ORG=soarndev
            export SENTRY_PROJECT='4508790454681600'

            sentry-cli releases new "$RELEASE_VERSION"
            sentry-cli releases set-commits --auto "$RELEASE_VERSION"
            sentry-cli releases set-deployed "$RELEASE_VERSION" --env production

workflows:
  version: 2
  ci-cd:
    jobs:
      - changesets-version # Renamed job in workflow too
      - build-and-push:
          requires:
            - changesets-version
      - sentry-release:
          requires:
            - build-and-push
