"""Added slack_username field to User model

Revision ID: 566b4c36327f
Revises: df4ca31f0adb
Create Date: 2025-02-05 16:52:49.067811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision = '566b4c36327f'
down_revision = 'df4ca31f0adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

    # Update existing records to set slack_username to username
    user_table = table('user',
                       column('id', sa.Integer),
                       column('username', sa.String),
                       column('slack_username', sa.String))

    connection = op.get_bind()
    connection.execute(
        user_table.update().values(slack_username=user_table.c.username)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('slack_username')

    # ### end Alembic commands ###
