name: Docker Build, Push & Sentry Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'
    pull_request:
      branches:
        - 'master'

permissions:
  contents: write
  packages: write

jobs:
  docker-build-push-sentry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: soarn/ctime

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push To Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Sentry CLI
        run: pip install --upgrade sentry-cli

      - name: Create Sentry release
        run: sentry-cli releases new ${{ steps.meta.outputs.tags }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: soarndev
          SENTRY_PROJECT: ctime

      - name: Associate commits with Sentry release
        run: sentry-cli releases set-commits --auto ${{ steps.meta.outputs.tags }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: soarndev
          SENTRY_PROJECT: ctime

      - name: Finalize Sentry release
        run: sentry-cli releases finalize ${{ steps.meta.outputs.tags }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: soarndev
          SENTRY_PROJECT: ctime
