name: CI/CD - Docker Build & Sentry Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Sentry CLI
        run: pip install sentry-cli

      - name: Create Sentry Release
        id: sentry-release
        run: |
          RELEASE_VERSION="${GITHUB_SHA::7}"
          sentry-cli releases new "$RELEASE_VERSION"
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          sentry-cli releases set-commits --auto "$RELEASE_VERSION"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: soarndev
          SENTRY_PROJECT: 4508790454681600

      - name: Build Docker image
        run: docker compose build

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request' # Only push on pushes/releases, not PRs
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Push to Docker Hub
        if: github.event_name != 'pull_request' # Only push on pushes/releases, not PRs
        run: |
          IMAGE_NAME=soarn/ctime:latest
          RELEASE_VERSION="${{ steps.sentry-release.outputs.release_version }}"
          TAGGED_IMAGE_NAME=soarn/ctime:"$RELEASE_VERSION"
          docker tag app "$IMAGE_NAME"
          docker push "$IMAGE_NAME"
          docker tag app "$TAGGED_IMAGE_NAME"
          docker push "$TAGGED_IMAGE_NAME"

      - name: Login to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' # Only push on pushes/releases, not PRs
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry (GHCR)
        if: github.event_name != 'pull_request' # Only push on pushes/releases, not PRs
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ctime:latest
          RELEASE_VERSION="${{ steps.sentry-release.outputs.release_version }}"
          TAGGED_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ctime:"$RELEASE_VERSION"
          docker tag app "$IMAGE_NAME"
          docker push "$IMAGE_NAME"
          docker tag app "$TAGGED_IMAGE_NAME"
          docker push "$TAGGED_IMAGE_NAME"

      - name: Set Sentry Release Deployed
        if: github.event_name != 'pull_request' # Only set deployed on pushes/releases, not PRs
        run: sentry-cli releases set-deployed --auto ${{ steps.sentry-release.outputs.release_version }} --environment=production
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: soarndev
          SENTRY_PROJECT: 4508790454681600
